name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract version from GitHub release tag
        id: get_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # v1.0.0 形式の場合、v を削除して 1.0.0 にする
          VERSION=${TAG#v}
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Validate tag format
        run: |
          if [[ ! "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Tag must follow vX.Y.Z format."
            exit 1
          fi

      - run: npm ci

      - name: Update package version
        run: npm version $VERSION --no-git-tag-version
        env:
          VERSION: ${{ env.VERSION }}

      - name: Check package.json
        run: cat package.json

      - name: Publish to NPM
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
